# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d38b0b07f368a4de8b9aa860893d51e5305e2f410ab276726398ae416ef46cbcb1a80438c4ebc6c93358aa74ed1833a2532ec1e72c91b772b4b993a8e58c291
  stripe_publishable_key: pk_test_8ddBwVIbysYnJZDptKFn9Lk7
  stripe_secret_key: sk_test_Uzvv4iwNxIbvCrf5iOzOoSsr

test:
  secret_key_base: d3b972478d75851e0abdb39eb5af02be04e25c54914afdf777ee765ac531becded53ceed161e835bafb675b27f5e74dff36ab1de89b10213a553f485dda67d66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV['stripe_publishable_key'] %>
  stripe_secret_key: <%= ENV['stripe_publishable_key'] %>
